./src/renderer/init_display.c
./src/renderer/transform.c
./src/renderer/render_shape.c
./src/renderer/init_setting.c
./src/renderer/draw.c
./src/renderer/orientation.c
./src/renderer/fill_pixels.c
./src/renderer/projection.c
./src/renderer/render_scene.c
./src/renderer/camera.c
./src/renderer/threads.c
./src/intersections/normal.c
./src/intersections/texture.c
./src/intersections/normal_map.c
./src/parse/utils2.c
./src/parse/texture2.c
./src/parse/shape2.c
./src/parse/shape_errors.c
./src/parse/settings2.c
./src/parse/utils1.c
./src/parse/scene.c
./src/parse/texture1.c
./src/parse/settings1.c
./src/parse/shape1.c
./src/parse/spotlight.c
./src/parse/utils4.c
./src/parse/elements1.c
./src/parse/error.c
./src/parse/settings_error.c
./src/parse/attributes2.c
./src/parse/settings_validation2.c
./src/parse/elements2.c
./src/parse/attribute_errors.c
./src/parse/utils3.c
./src/parse/element_errors.c
./src/parse/attributes1.c
./src/parse/settings_validation1.c
./src/parse/settings3.c
./src/math/min_max.c
./src/shading/color_operations.c
./src/shading/vector.c
./src/shading/cube_faces.c
./src/shading/cube_mapping.c
./src/shading/reflection.c
./src/shading/shape_texture.c
./src/shading/utils.c
./src/shading/modification2.c
./src/shading/patterns.c
./src/shading/transformations.c
./src/shading/modification1.c
./src/shading/matrix.c
./src/main.c
./src/linear_algebra/inverse_matrix.c
./src/linear_algebra/matrix_transformation.c
./src/linear_algebra/matrix_operation.c
./src/linear_algebra/vector_arithmetic.c
./src/linear_algebra/determinant_matrix.c
./src/linear_algebra/vector_operation.c
./src/interaction/setup_hooks.c
./src/interaction/mouse.c
./src/interaction/hook_rotate.c
./src/interaction/ray_intersection.c
./src/interaction/toggle_key.c
./src/interaction/lookat_animation.c
./src/interaction/hook_move.c
./src/interaction/scale_change.c
./src/interaction/toggle_shape.c
./src/interaction/key_press.c
./src/interaction/loop_hook_transform.c
./src/interaction/lookat.c
./src/interaction/free_textures.c
./src/interaction/camera_controls.c
./src/interaction/free_utils.c
./src/interaction/mouse_utils.c
./src/interaction/lights.c
./src/interaction/shape.c
./src/interaction/loop_hook.c
./src/collision/fill_vtx1.c
./src/collision/intersection_compute.c
./src/collision/check_collision.c
./src/collision/cylindrical_plane_collision.c
./src/collision/fill_vtx2.c
./src/collision/glk_support.c
./src/collision/gjk.c
./src/collision/sameshape_collision.c
./src/collision/on_origin.c
./src/collision/secondary_plane.c
./src/collision/test_box_overlap.c
./src/collision/collision.c
./src/collision/tetrahedron_on_origin.c
./src/collision/triangle_on_origin.c
./src/collision/cylinder_sphere_collision.c
./src/collision/test_box_axes.c
